[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2021"
default-run = "server"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[package.metadata.docs.rs]
rustdoc-args = [
    "--no-defaults",
    "--passes", "collapse-docs",
    "--passes", "unindent-comments"
]

[dependencies]
anyhow = "1.0"
base64 = "0.13"
cargo-registry-markdown = { path = "cargo-registry-markdown" }
cargo-registry-s3 = { path = "cargo-registry-s3" }
chrono = { version = "0.4.19", features = ["serde"] }
clap = "=3.0.0-beta.5"

conduit = "0.10.0"
conduit-conditional-get = "0.10.0"
conduit-cookie = "0.10.0"
conduit-git-http-backend = "0.10.0"
conduit-hyper = "0.4.1"
conduit-middleware = "0.10.0"
conduit-router = "0.10.0"
conduit-static = "0.10.0"

cookie = { version = "0.16.0-rc.1", features = ["secure"] }
dashmap = { version = "4.0.2", features = ["raw-api"] }
derive_deref = "1.1.1"
dialoguer = "0.9"
diesel = { version = "1.4.8", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "1.0.1"
diesel_migrations = { version = "1.4.0", features = ["postgres"] }
dotenv = "0.15"
flate2 = "1.0"
futures-channel = { version = "0.3.17", default-features = false }
futures-util = "0.3"
git2 = "0.13.24"
hex = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http1"] }
indexmap = { version = "1.7.0", features = ["serde-1"] }
tikv-jemallocator = { version = "0.4.1", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
lettre = { version = "0.10.0-rc.4", default-features = false, features = ["file-transport", "smtp-transport", "native-tls", "hostname", "builder"] }
license-exprs = "1.6"
minijinja = "0.8.2"
moka = "0.6.1"
oauth2 = { version = "4.1.0", default-features = false, features = ["reqwest"] }
parking_lot = "0.11"
prometheus = { version = "0.13.0", default-features = false }
rand = "0.8"
reqwest = { version = "0.11", features = ["blocking", "gzip", "json"] }
scheduled-thread-pool = "0.2.5"
semver = { version = "1.0.4", features = ["serde"] }
sentry = { version = "0.23.0", features = ["tracing"] }
sentry-conduit = { version = "0.4.0", default-features = false }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"
sha2 = "0.9"
swirl = { git = "https://github.com/sgrif/swirl.git", rev = "e87cf37" }
tar = "0.4.37"
tempfile = "3"
thiserror = "1.0.30"
tokio = { version = "1.13.0", features = ["net", "signal", "io-std", "io-util", "rt-multi-thread", "macros"]}
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
url = "2.2"

[dev-dependencies]
claim = "0.5"
conduit-test = "0.10.0"
hyper-tls = "0.5"
lazy_static = "1.4"
tokio = "1.13.0"
tower-service = "0.3.1"

[build-dependencies]
diesel = { version = "1.4.8", features = ["postgres"] }
diesel_migrations = { version = "1.4.0", features = ["postgres"] }
dotenv = "0.15"
