[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2018"
default-run = "server"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[package.metadata.docs.rs]
rustdoc-args = [
    "--no-defaults",
    "--passes", "collapse-docs",
    "--passes", "unindent-comments"
]

[dependencies]
ammonia = "3.0.0"
anyhow = "1.0"
base64 = "0.13"
cargo-registry-s3 = { path = "src/s3", version = "0.2.0" }
chrono = { version = "0.4.0", features = ["serde"] }
clap = "=3.0.0-beta.2"
comrak = { version = "0.10", default-features = false }

conduit = "0.9.0-alpha.5"
conduit-conditional-get = "0.9.0-alpha.3"
conduit-cookie = "0.9.0-alpha.5"
conduit-git-http-backend = "0.9.0-alpha.2"
conduit-hyper = "0.3.0-alpha.7"
conduit-middleware = "0.9.0-alpha.4"
conduit-router = "0.9.0-alpha.6"
conduit-static = "0.9.0-alpha.3"

cookie = { version = "0.15", features = ["secure"] }
dashmap = { version = "4.0.2", features = ["raw-api"] }
derive_deref = "1.1.1"
dialoguer = "0.8"
diesel = { version = "1.4.0", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "1.0.0"
dotenv = "0.15"
flate2 = "1.0"
futures-channel = { version = "0.3.1", default-features = false }
futures-util = "0.3"
git2 = "0.13.0"
handlebars = "3.0.1"
hex = "0.4"
htmlescape = "0.3.1"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http1"] }
indexmap = "1.0.2"
jemallocator = { version = "0.3", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
lettre = { version = "0.10.0-beta.3", default-features = false, features = ["file-transport", "smtp-transport", "native-tls", "hostname", "builder"] }
license-exprs = "1.6"
oauth2 = { version = "=4.0.0-alpha.6", default-features = false, features = ["reqwest"] }
parking_lot = "0.11"
rand = "0.8"
reqwest = { version = "0.11", features = ["blocking", "gzip", "json"] }
scheduled-thread-pool = "0.2.0"
semver = { version = "0.10", features = ["diesel", "serde"] }
sentry = "0.22"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
sha2 = "0.9"
swirl = { git = "https://github.com/sgrif/swirl.git", rev = "e87cf37" }
tar = "0.4.16"
tempfile = "3"
tokio = { version = "1", features = ["net", "signal", "io-std", "io-util", "rt-multi-thread"]}
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
url = "2.1"

[dev-dependencies]
claim = "0.5"
conduit-test = "0.9.0-alpha.4"
diesel_migrations = { version = "1.3.0", features = ["postgres"] }
hyper-tls = "0.5"
lazy_static = "1.0"
tokio = "1"
tower-service = "0.3.0"

[build-dependencies]
diesel = { version = "1.3.0", features = ["postgres"] }
diesel_migrations = { version = "1.3.0", features = ["postgres"] }
dotenv = "0.15"
