[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2018"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[package.metadata.docs.rs]
rustdoc-args = [
    "--no-defaults",
    "--passes", "collapse-docs",
    "--passes", "unindent-comments"
]

[dependencies]
cargo-registry-s3 = { path = "src/s3", version = "0.2.0" }
rand = "0.7"
git2 = "0.13.0"
flate2 = "1.0"
semver = { version = "0.10", features = ["diesel", "serde"] }
url = "2.1"
tar = "0.4.16"
base64 = "0.12"

openssl = "0.10.13"
oauth2 = { version = "3.0.0", default-features = false, features = ["reqwest-010"] }
log = "0.4"
env_logger = "0.7"
hex = "0.4"
htmlescape = "0.3.1"
license-exprs = "^1.4"
dotenv = "0.15"
toml = "0.5"
diesel = { version = "1.4.0", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "1.0.0"
swirl = { git = "https://github.com/sgrif/swirl.git", rev = "e87cf37" }
serde_json = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
comrak = { version = "0.7", default-features = false }
ammonia = "3.0.0"
docopt = "1.0"
scheduled-thread-pool = "0.2.0"
derive_deref = { version = "1.0.0", git = "https://github.com/azriel91/derive_deref.git", rev = "63527ab" }
reqwest = { version = "0.10", features = ["blocking", "gzip", "json"] }
tempfile = "3"
parking_lot = "0.10"
jemallocator = { version = "0.3", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }

lettre = "0.9"
lettre_email = "0.9"
failure = "0.1.1"

conduit = "0.9.0-alpha.2"
conduit-conditional-get = "0.9.0-alpha.3"
conduit-cookie = "0.9.0-alpha.3"
cookie = { version = "0.13", features = ["secure"] }
conduit-middleware = "0.9.0-alpha.2"
conduit-router = "0.9.0-alpha.2"
conduit-static = "0.9.0-alpha.3"
conduit-git-http-backend = "0.9.0-alpha.2"
civet = "0.12.0-alpha.3"
conduit-hyper = "0.3.0-alpha.4"
http = "0.2"

futures-util = "0.3"
futures-channel = { version = "0.3.1", default-features = false }
tokio = { version = "0.2", default-features = false, features = ["net", "signal", "io-std"]}
hyper = "0.13"
ctrlc = { version = "3.0", features = ["termination"] }
indexmap = "1.0.2"
handlebars = "3.0.1"

[dev-dependencies]
conduit-test = "0.9.0-alpha.2"
hyper-tls = "0.4"
lazy_static = "1.0"
diesel_migrations = { version = "1.3.0", features = ["postgres"] }
tower-service = "0.3.0"
tokio = { version = "0.2", default-features = false, features = ["stream"]}

[build-dependencies]
dotenv = "0.15"
diesel = { version = "1.3.0", features = ["postgres"] }
diesel_migrations = { version = "1.3.0", features = ["postgres"] }
