[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2018"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[package.metadata.docs.rs]
rustdoc-args = [
    "--no-defaults",
    "--passes", "collapse-docs",
    "--passes", "unindent-comments"
]

[dependencies]
cargo-registry-s3 = { path = "src/s3", version = "0.2.0" }
rand = "0.6"
git2 = "0.8.0"
flate2 = "1.0"
semver = { version = "0.9", git = "https://github.com/steveklabnik/semver.git", features = ["diesel", "serde"] }
url = "1.2.1"
tar = "0.4.16"
base64 = "0.9"

openssl = "0.10.13"
oauth2 = "0.3"
log = "0.4"
env_logger = "0.5"
hex = "0.3"
htmlescape = "0.3.1"
license-exprs = "^1.4"
dotenv = "0.11.0"
toml = "0.4"
diesel = { version = "1.4.0", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "1.0.0"
swirl = { git = "https://github.com/sgrif/swirl.git", rev = "de5d8bb" }
serde_json = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
comrak = { version = "0.4.0", default-features = false }
ammonia = "2.0.0"
docopt = "1.0"
scheduled-thread-pool = "0.2.0"
derive_deref = "1.0.0"
reqwest = "0.9.1"
tempdir = "0.3.7"
parking_lot = "0.7.1"
jemallocator = { version = "0.1.8", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
jemalloc-ctl = "0.2.0"

lettre = "0.9"
lettre_email = "0.9"
failure = "0.1.1"

conduit = "0.8"
conduit-conditional-get = "0.8"
conduit-cookie = "0.8.5"
cookie = "0.11"
conduit-middleware = "0.8"
conduit-router = "0.8"
conduit-static = "0.8"
conduit-git-http-backend = "0.8"
civet = "0.9"
conduit-hyper = "0.1.3"

futures = "0.1"
tokio = "0.1"
hyper = "0.12"
ctrlc = { version = "3.0", features = ["termination"] }
indexmap = "1.0.2"
handlebars = "2.0.1"

[dev-dependencies]
conduit-test = "0.8"
hyper-tls = "0.3"
lazy_static = "1.0"
tokio-core = "0.1"

[build-dependencies]
dotenv = "0.11"
diesel = { version = "1.3.0", features = ["postgres"] }
diesel_migrations = { version = "1.3.0", features = ["postgres"] }
