version: "3"

x-backend: &backend
  build:
    context: .
    dockerfile: backend.Dockerfile
  environment:
    DEV_DOCKER: "true"
    DATABASE_URL: postgres://postgres:password@postgres/cargo_registry
    SESSION_KEY: badkeyabcdefghijklmnopqrstuvwxyzabcdef
    GIT_REPO_URL: file://./tmp/index-bare
    GH_CLIENT_ID: ""
    GH_CLIENT_SECRET: ""
    WEB_ALLOWED_ORIGINS: http://localhost:8888,http://localhost:4200
  links:
    - postgres
  volumes:
    # Mount the src/ directory so we don't have to rebuild the Docker image
    # when we want to change some code
    - ./src:/app/src:ro

    - index:/app/tmp
    - cargo-cache:/usr/local/cargo/registry
    - target-cache:/app/target

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: cargo_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      start_period: 30s

  backend:
    <<: *backend
    ports:
      - 8888:8888
    healthcheck:
      test: curl http://backend:8888/api/v1/site_metadata
      interval: 5s
      start_period: 300s

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    entrypoint: yarn start -- --proxy http://backend:8888
    links:
      - backend
    ports:
      - 4200:4200
    volumes:
      # Mount the app/ directory so live reload works
      - ./app:/app/app:ro
    healthcheck:
      test: wget http://frontend:4200/ -O /dev/null
      interval: 5s
      start_period: 120s

volumes:
  postgres-data:
  cargo-cache:
  target-cache:
  index:
