[package]

name = "cargo-registry-s3"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Interaction between crates.io and S3 for storing crate files"
edition = "2018"

[lib]

name = "s3"
path = "lib.rs"

[dependencies]
base64 = "0.13"
chrono = "0.4"
sha-1 = "0.9"
hmac = "0.8"
reqwest = { version = "0.10", features = ["blocking"] }
