name: CI

on:
  push:
    branches:
      - auto
      - master
      - try

  pull_request:

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-20.04
    env:
      JOBS: 1 # See https://git.io/vdao3 for details.

      # Percy secrets are included here to enable Percy's GitHub integration
      # on community-submitted PRs
      PERCY_TOKEN: 0d8707a02b19aebbec79bb0bf302b8d2fa95edb33169cfe41b084289596670b1
      PERCY_PROJECT: crates-io/crates.io

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install node modules
        run: yarn install

      - name: Lint
        run: |
          yarn lint:hbs
          yarn lint:js
          yarn lint:deps

      - name: Run percy exec
        if: github.repository == 'rust-lang/crates.io'
        run: npx percy exec -- npm run test-coverage

      - name: test-coverage
        if: github.repository != 'rust-lang/crates.io'
        run: yarn test-coverage

  embroider:
    name: Frontend (embroider)
    runs-on: ubuntu-20.04
    env:
      USE_EMBROIDER: 'true'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: yarn install

      # `yarn test` currently does not work due to https://github.com/embroider-build/embroider/issues/677
      - run: yarn build
        continue-on-error: true

  backend-lint:
    name: Backend (linting)
    runs-on: ubuntu-20.04

    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v2

      # Current size as of 2021-02-15: ~105 MB
      - name: Cache cargo registry and git deps
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            ~/.cargo/git/db
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust
        run: |
          rustup set profile minimal
          # Pin to older version until a clippy regression is fixed
          rustup update 1.53.0
          rustup default 1.53.0

      - id: rustc
        run:
          echo "::set-output name=version::$(rustc -V)"

      - name: Cache cargo build
        uses: actions/cache@v2.1.6
        with:
          path: target
          key: v2-${{ runner.os }}-cargo-clippy-${{ steps.rustc.outputs.version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v2-${{ runner.os }}-cargo-clippy-${{ steps.rustc.outputs.version }}-

      - run: rustup component add rustfmt
      - run: rustup component add clippy

      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets --all-features --all

  backend:
    name: Backend
    runs-on: ubuntu-20.04
    strategy:
      # TODO: [ci] should be true if GitHub Actions supports ""allow failures" on matrix
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta

    env:
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://postgres:postgres@localhost/cargo_registry_test
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost/cargo_registry_test
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: "-D warnings"
      MALLOC_CONF: "background_thread:true,abort_conf:true,abort:true,junk:true"

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Cleanup pre-installed Rust toolchains
        # The pre-installed toolchain is under root permission, and this would
        # make tarball fail to extract. Here we remove the symlink and install
        # our own Rust toolchain if necessary.
        run: |
          which rustup
          which cargo
          if [[ -L "$HOME/.cargo" && -L "$HOME/.rustup" ]]; then
              rm -v "$HOME/.rustup"
              rm -v "$HOME/.cargo"
          fi
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Cache `diesel` binary
      #
      # The other binaries (like `rustc`) will be overwritten by rustup.
      #
      # Current size as of 2021-02-15: ~15 MB
      - name: Cache cargo binaries
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ matrix.rust }}-${{ hashFiles('.diesel_version') }}-v3

      # Current size as of 2021-02-15: ~105 MB
      - name: Cache cargo registry and git deps
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            ~/.cargo/git/db
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install ${{ matrix.rust }} Rust
        run: |
          if [[ ! -d "$HOME/.cargo" || ! -d "$HOME/.rustup" ]]; then
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
              sh rustup-init.sh -y --default-toolchain none
          fi
          rustup set profile minimal
          rustup update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}

      - id: rustc
        run:
          echo "::set-output name=version::$(rustc -V)"

      # Current size as of 2021-02-12: ~325 MB
      - name: Cache cargo build
        uses: actions/cache@v2.1.6
        with:
          path: target
          key: v2-${{ runner.os }}-cargo-build-target-${{ steps.rustc.outputs.version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v2-${{ runner.os }}-cargo-build-target-${{ steps.rustc.outputs.version }}-

      - name: Setup database
        run: |
          which diesel || cargo install diesel_cli --vers $(cat .diesel_version) --no-default-features --features postgres --debug
          diesel database setup --locked-schema

      - name: Install cargo-tarpaulin
        if: matrix.rust == 'stable'
        run: which cargo-tarpaulin || cargo install cargo-tarpaulin --version ~0.18.0-alpha.3

      - name: Run tests (with coverage report)
        if: matrix.rust == 'stable'
        run: cargo tarpaulin --avoid-cfg-tarpaulin

      - name: Run tests
        if: matrix.rust != 'stable'
        run: cargo test

      - name: Prune unnecessary cache
        run: script/ci/prune-cache.sh


  # These jobs doesn't actually test anything, but they're only used to tell
  # bors the build completed, as there is no practical way to detect when a
  # workflow is successful listening to webhooks only.
  #
  # ALL THE PREVIOUS JOBS NEEDS TO BE ADDED TO THE `needs` SECTION OF THIS JOB!

  end-success:
    name: bors build finished
    if: success()
    runs-on: ubuntu-latest
    needs: [frontend, backend, backend-lint]

    steps:
      - name: Mark the job as successful
        run: exit 0

  end-failure:
    name: bors build finished
    if: "!success()"
    runs-on: ubuntu-latest
    needs: [frontend, backend, backend-lint]

    steps:
      - name: Mark the job as a failure
        run: exit 1
